from dataclasses import dataclass
from dataclasses import field
from pathlib import Path
import yaml


@dataclass(frozen=True)
class ImagePairConfig:
    """Manage data configuration for a single image pair, including two input images and corresponding ground truth file.

    Attributes:
        src_path (str | Path): Filename of the first source image, e.g., "1a_notredame.jpg".
        dst_path (str | Path): Filename of the second destination image, e.g., "1b_notredame.jpg".
        gt_path (str | Path): Ground truth filename for this image pair, e.g., "notredame.pkl".

            **Must use `pickle.load(f, encoding="latin1")`**, otherwise uint8 data generated by MATLAB cannot be decoded correctly.
    Example:
        >>> pickle.load(open("notredame.pkl", "rb"), encoding="latin1")

    .. Note::
        Deserialization returns a dict with the following keys:
        - x1 (np.ndarray): x coordinates of feature points in image A
        - y1 (np.ndarray): y coordinates of feature points in image A
        - x2 (np.ndarray): x coordinates of corresponding matching points in image B
        - y2 (np.ndarray): y coordinates of corresponding matching points in image B
    """

    src_path: str | Path
    dst_path: str | Path
    gt_path: str | Path

    def __post_init__(self) -> None:
        if isinstance(self.src_path, str):
            object.__setattr__(self, "src_path", Path(self.src_path))
        if isinstance(self.dst_path, str):
            object.__setattr__(self, "dst_path", Path(self.dst_path))
        if isinstance(self.gt_path, str):
            object.__setattr__(self, "gt_path", Path(self.gt_path))


@dataclass(frozen=True)
class OutputConfig:
    """Manage output directory structure for results and figures.

    Attributes:
        output_dir (str | Path): Output root directory, default ./outputs, supports string or Path object input.
        figure_dir (Path): Pre-computed complete path for figures subdirectory, auto-set in __post_init__.
    """

    output_dir: str | Path = Path("./outputs")
    figure_dir: str | Path = str("figures")

    def __post_init__(self) -> None:
        # Convert output_dir to Path object
        if isinstance(self.output_dir, str):
            object.__setattr__(self, "output_dir", Path(self.output_dir))

        # Pre-compute complete path for figures subdirectory (relative: figures)
        output_dir_path = Path(self.output_dir)
        concat_figure_dir = output_dir_path.joinpath(self.figure_dir)

        # Store computed complete path as attribute
        object.__setattr__(self, "figure_dir", concat_figure_dir)


@dataclass(frozen=True)
class PathConfig:
    """Manage project input paths and image pair configuration.

    Attributes:
        data_dir (str | Path): Image data directory, default ./data, supports string or Path object input.
        ground_truth_dir (str | Path): Ground truth data directory, default ./ground_truth, supports string or Path object input.
        output (OutputConfig): Output directory structure and sub-paths configuration.
        image_pairs (list[ImagePairConfig]): List of image pairs, default includes notredame/rushmore/gaudi sets.
    """

    data_dir: str | Path = Path("./data")
    ground_truth_dir: str | Path = Path("./ground_truth")
    output: OutputConfig = field(default_factory=OutputConfig)
    image_pairs: list[ImagePairConfig] = field(
        default_factory=lambda: [
            ImagePairConfig(
                src_path="1a_notredame.jpg",
                dst_path="1b_notredame.jpg",
                gt_path="notredame.pkl",
            ),
            ImagePairConfig(
                src_path="2a_rushmore.jpg",
                dst_path="2b_rushmore.jpg",
                gt_path="rushmore.pkl",
            ),
            ImagePairConfig(
                src_path="3a_gaudi.jpg", dst_path="3b_gaudi.jpg", gt_path="gaudi.pkl"
            ),
        ]
    )

    def __post_init__(self) -> None:
        # Convert parent directories to Path objects
        if isinstance(self.data_dir, str):
            object.__setattr__(self, "data_dir", Path(self.data_dir))
        if isinstance(self.ground_truth_dir, str):
            object.__setattr__(self, "ground_truth_dir", Path(self.ground_truth_dir))

        # Concatenate data_dir / ground_truth_dir to each image pair filename to generate complete paths
        data_dir = Path(self.data_dir)
        gt_dir = Path(self.ground_truth_dir)
        concat_pairs = [
            ImagePairConfig(
                src_path=data_dir.joinpath(pair.src_path),
                dst_path=data_dir.joinpath(pair.dst_path),
                gt_path=gt_dir.joinpath(pair.gt_path),
            )
            for pair in self.image_pairs
        ]
        object.__setattr__(self, "image_pairs", concat_pairs)


@dataclass(frozen=True)
class ExperimentConfig:
    """Experiment hyperparameters for the feature matching pipeline.

    Attributes:
        scale_factor (float): Resize scale applied to input images.
        num_points (int): Maximum number of Harris interest points to detect per image.
        num_vis (int): Number of top matches to visualize and evaluate.
    """

    scale_factor: float = 0.5
    num_points: int = 4500
    num_vis: int = 100


@dataclass(frozen=True)
class LoggingConfig:
    """Manage logging behavior and output directory configuration.

    Attributes:
        log_dir (str | Path): Log output directory, default ./outputs/logs, supports string or Path object input.
        level (str): Log level, default "DEBUG", options "DEBUG"/"INFO"/"WARNING"/"ERROR"/"CRITICAL".
        retention (str): Log file retention time, default "7 days", supports natural language format, logs older than this will be auto-deleted.
        file_pattern (str): Log filename pattern, default "{time:YYYY-MM-DD_HH-mm-ss}.log", uses loguru time formatting, includes hour-minute-second to avoid conflicts from multiple runs on the same day.
    """

    log_dir: str | Path = Path("./outputs/logs")
    level: str = "DEBUG"
    retention: str = "7 days"
    file_pattern: str = "{time:YYYY-MM-DD_HH-mm-ss}.log"

    def __post_init__(self) -> None:
        if isinstance(self.log_dir, str):
            object.__setattr__(self, "log_dir", Path(self.log_dir))


@dataclass(frozen=True)
class SceneConfig:
    """Scene recognition dataset configuration.

    Attributes:
        data_dir (str | Path): Root directory containing ``train/`` and ``test/``
            subdirectories (e.g. ``./data``).
        train_dir (Path): Pre-computed path to the training subdirectory.
        test_dir (Path): Pre-computed path to the testing subdirectory.
    """

    data_dir: str | Path = Path("./data")
    train_dir: Path = Path("train")
    test_dir: Path = Path("test")

    def __post_init__(self) -> None:
        if isinstance(self.data_dir, str):
            object.__setattr__(self, "data_dir", Path(self.data_dir))

        data_dir = Path(self.data_dir)
        object.__setattr__(self, "train_dir", data_dir.joinpath(self.train_dir))
        object.__setattr__(self, "test_dir", data_dir.joinpath(self.test_dir))


@dataclass(frozen=True)
class SceneRecConfig:
    """Scene recognition pipeline hyperparameters and cache paths.

    Attributes:
        vocab_size (int): Size of visual vocabulary (k-means clusters), default 100.
        cache_dir (str | Path): Directory for caching features and vocabulary, default ``./data``.
        tiny_train_path (str | Path): Tiny image train features cache path, relative or absolute, default ``train_tiny.npy``; resolved to full path in __post_init__.
        tiny_test_path (str | Path): Tiny image test features cache path, default ``test_tiny.npy``; resolved to full path in __post_init__.
        k_tiny_images (int): k for k-NN in tiny image pipeline, default 3.
        k_bag_of_sifts (int): k for k-NN in BoF pipeline, default 15.
        svm_c (float): Regularization parameter C for LinearSVM, default 0.1.
        num_per_cat (int | None): Limit images per category for training (None = all), default 100.
        stride (int): Sampling stride for dense SIFT extraction, default 20.
        results_dir (str | Path): Output directory for confusion matrix heatmap, default ``./results``.
        vocab_path (str | Path): Vocabulary cache path, auto-generated from ``vocab_size``.
        bof_train_path (str | Path): BoF train features cache path, auto-generated from ``vocab_size``.
        bof_test_path (str | Path): BoF test features cache path, auto-generated from ``vocab_size``.
        confusion_matrix_path (str | Path): Confusion matrix heatmap path, resolved from ``results_dir``.
        categories (list[str]): Full category names for classification.
        abbr_categories (list[str]): Abbreviated names for confusion matrix display.
    """

    vocab_size: int = 100
    cache_dir: str | Path = Path("./data")
    tiny_train_path: str | Path = Path("train_tiny.npy")
    tiny_test_path: str | Path = Path("test_tiny.npy")
    k_tiny_images: int = 3
    k_bag_of_sifts: int = 15
    svm_c: float = 0.1
    num_per_cat: int | None = 100
    stride: int = 20
    results_dir: str | Path = Path("./results")
    vocab_path: str | Path = Path("vocab_100.npy")
    bof_train_path: str | Path = Path("train_bof_100.npy")
    bof_test_path: str | Path = Path("test_bof_100.npy")
    confusion_matrix_path: str | Path = Path("confusion_matrix.png")
    categories: list[str] = field(
        default_factory=lambda: [
            "Kitchen", "Store", "Bedroom", "LivingRoom", "Office",
            "Industrial", "Suburb", "InsideCity", "TallBuilding", "Street",
            "Highway", "OpenCountry", "Coast", "Mountain", "Forest",
        ]
    )
    abbr_categories: list[str] = field(
        default_factory=lambda: [
            "Kit", "Sto", "Bed", "Liv", "Off",
            "Ind", "Sub", "Ins", "Tal", "Str",
            "Hig", "Ope", "Coa", "Mou", "For",
        ]
    )

    def __post_init__(self) -> None:
        if isinstance(self.cache_dir, str):
            object.__setattr__(self, "cache_dir", Path(self.cache_dir))
        if isinstance(self.results_dir, str):
            object.__setattr__(self, "results_dir", Path(self.results_dir))

        cache = Path(self.cache_dir)
        results = Path(self.results_dir)
        # Overwrite fields with full paths resolved from cache_dir / results_dir
        object.__setattr__(self, "vocab_path", cache.joinpath(f"vocab_{self.vocab_size}.npy"))
        object.__setattr__(self, "tiny_train_path", cache.joinpath(Path(self.tiny_train_path)))
        object.__setattr__(self, "tiny_test_path", cache.joinpath(Path(self.tiny_test_path)))
        object.__setattr__(self, "bof_train_path", cache.joinpath(f"train_bof_{self.vocab_size}.npy"))
        object.__setattr__(self, "bof_test_path", cache.joinpath(f"test_bof_{self.vocab_size}.npy"))
        object.__setattr__(self, "confusion_matrix_path", results.joinpath(Path(self.confusion_matrix_path)))


@dataclass(frozen=True)
class AppConfig:
    """
    Aggregate global configuration entry point.

    Attributes:
        paths (PathConfig): Path and image pair configuration.
        scene (SceneConfig): Scene recognition dataset configuration.
        logging (LoggingConfig): Logging-related configuration.
    """

    paths: PathConfig = field(default_factory=PathConfig)
    scene: SceneConfig = field(default_factory=SceneConfig)
    scene_rec: SceneRecConfig = field(default_factory=SceneRecConfig)
    experiment: ExperimentConfig = field(default_factory=ExperimentConfig)
    logging: LoggingConfig = field(default_factory=LoggingConfig)

    @classmethod
    def load_from_yaml(cls, yaml_path: str | Path) -> "AppConfig":
        try:
            with open(yaml_path, "r", encoding="utf-8") as f:
                config_dict = yaml.safe_load(f) or {}
                print(
                    f"\n\033[1;92m[SUCCESS] Configuration file loaded successfully: {yaml_path}\033[0m\n"
                )
        except yaml.YAMLError as e:
            raise ValueError(
                f"\033[1;91mInvalid YAML format in {yaml_path}: {e}\033[0m"
            ) from e
        except FileNotFoundError as e:
            raise ValueError(
                f"\033[1;91mConfiguration file not found: {yaml_path}\033[0m"
            ) from e

        paths_dict = config_dict.get("paths", {})
        scene_dict = config_dict.get("scene", {})
        scene_rec_dict = config_dict.get("scene_rec", {})
        experiment_dict = config_dict.get("experiment", {})
        logging_dict = config_dict.get("logging", {})

        # Process image_pairs list: convert dict list to ImagePairConfig object list
        image_pairs_list = paths_dict.get("image_pairs", [])
        paths_dict["image_pairs"] = [
            ImagePairConfig(**pair) for pair in image_pairs_list
        ]

        # Process output config: convert dict to OutputConfig object
        output_dict = paths_dict.get("output", {})
        paths_dict["output"] = OutputConfig(**output_dict)

        return cls(
            paths=PathConfig(**paths_dict),
            scene=SceneConfig(**scene_dict),
            scene_rec=SceneRecConfig(**scene_rec_dict),
            experiment=ExperimentConfig(**experiment_dict),
            logging=LoggingConfig(**logging_dict),
        )
