paths:
  data_dir: ./data
  ground_truth_dir: ./ground_truth
  output:
    output_dir: ./outputs
    figure_dir: figures
  image_pairs:
    - src_path: 1a_notredame.jpg
      dst_path: 1b_notredame.jpg
      gt_path: notredame.pkl
    - src_path: 2a_rushmore.jpg
      dst_path: 2b_rushmore.jpg
      gt_path: rushmore.pkl
    - src_path: 3a_gaudi.jpg
      dst_path: 3b_gaudi.jpg
      gt_path: gaudi.pkl

scene:
  data_dir: ./data

scene_rec:
  vocab_size: 200
  cache_dir: ./data
  k_tiny_images: 3
  k_bag_of_sifts: 15
  svm_c: 0.1
  num_per_cat: 100
  stride: 20

experiment:
  scale_factor: 0.5
  num_points: 4500
  num_vis: 100

logging:
  log_dir: ./outputs/logs
  level: DEBUG
  retention: 7 days
  file_pattern: "{time:YYYY-MM-DD_HH-mm-ss}.log"
